### ISSUE TITLE
App lets you see and make edits to board after signing out 

### ISSUE THREAD

**Issue by jussisaurio** [raimohanska/ourboard#155]
Create restricted board
Go to board. Sign out. UI still lets you see the content and do stuff.
Do something, e.g. create a note.
Refresh.
UI still lets you see the board (although backend logs “Access denied”

Suspecting this has to do with the new synchronization mechanism

**Comment by jussisaurio** [comment]
Resolved it like this for the time being:
https://github.com/raimohanska/ourboard/commit/7261834f87c9dca59467dd711697af56a4727409
(Show a different message if user has local copy of restricted board and is logged out)

**Comment by raimohanska** [comment]
I think that's a good solution. Further, if the user intentionally signs out, we should probably clear all private boards from local storage, amirite?

**Comment by raimohanska** [comment]
Added clearing local boards on login. Try!
