### ISSUE TITLE
Text doesn't wrap in a sticky note when pasting

### ISSUE THREAD

**Issue by timojaask** [raimohanska/ourboard#175]
<img width="313" alt="Screen Shot 2021-10-15 at 8 50 44 AM" src="https://user-images.githubusercontent.com/3090208/137516560-08b41ea0-bbb2-4c28-96b0-63d6e0d542ed.png">

In the screenshot above, both sticky notes have exactly the same text. The first one was entered entirely by typing "OOOOO OOOOO". The second one was entered by typing the first word "OOOOO " and then pasting from clipboard the second word "OOOOO".

I'm guessing that the text measurement step is only done when you type, and omitted when pasting?

**Comment by raimohanska** [comment]
Interestingly in the latter case, the DOM element ends up having a non-breaking space between the OOOOOs.

![image](https://user-images.githubusercontent.com/292964/137630662-00891e64-2ffa-4d0e-a6f5-e703371e71c5.png)

**Comment by raimohanska** [comment]
Already when the space after the first OOOOO is input by pressing the spacebar, it's actually an `&nbsp;` which is then converted to a normal space after typing more characters. In case of paste, it will remaing `&nbsp;`. Oh the quirks.
