### ISSUE TITLE
Missing menu bar 

### ISSUE THREAD

**Issue by datduyng** [raimohanska/ourboard#199]
# Missing menu bar when first run app

## Screenshot

YOUR SCREENSHOT HERE:
![CleanShot 2022-04-20 at 16 51 47@2x](https://user-images.githubusercontent.com/35666615/164320752-c418b46a-b569-46ec-84ee-8ee8dc721308.png)

## A sentence description of the problem
I am try to run the code base by following the read me. Here is what I did

- docker compose up
- yarn install
- yarn dev 

What I notice

- `GOOGLE_CLIENT_ID missing, cannot verify Google login token` Does this mean I can't develop the app without GOOGLE_CLIENT_ID?
- lots of Socket errors 
<img width="830" alt="CleanShot 2022-04-20 at 16 53 47@2x" src="https://user-images.githubusercontent.com/35666615/164321052-d42291da-cd20-4eb2-a4a7-bc4131cc226b.png">

That's it! Thanks.

**Comment by raimohanska** [comment]
The menu etc will be shown once the board connection is fully initialized IIRC. So most likely related to the socket errors. Maybe your server-side log will reveal the actual error.

Google creds shouldn't be required for running.
