### ISSUE TITLE
Can't ctrl-z a note on firefox

### ISSUE THREAD

**Issue by seguri** [raimohanska/ourboard#200]
## Url

-   https://www.ourboard.io/b/b8ff23ed-5687-4b3c-a5fc-e833d309aab4

## Description

Short DESCRIPTION: Can't undo sticky note on firefox

If I press "a", esc, ctrl-z, the new area disappears.
If I press "n", esc, ctrl-z, the text is not selected anymore, but the note stays there. Repeating ctrl-z doesn't help.

**Comment by raimohanska** [comment]
Thanks for reporting this. 

Reproducable on Firefox, does not occur on Chrome.

The problem seems to be related to focus - if you click outside the note after creation and then Cmd-Z, the note will be deleted correctly.

**Comment by seguri** [comment]
A mouse-less solution would be ideal :)

**Comment by raimohanska** [comment]
Yes sure! Please also note that this is a hobby project for me and I haven't had much time lately for OurBoard. All contributions are welcome!

**Comment by seguri** [comment]
No worries, take all the time you need! I can't contribute to a Typescript project right now, maybe one day :)

**Comment by raimohanska** [comment]
Hmm. Cannot reproduce anymore. Has it been fixed by the Firefox team maybe? @seguri want to check if this is good now?

**Comment by seguri** [comment]
I don't have Firefox installed right now, but I can't reproduce it on Mullvad Browser. I guess it's fixed :)

**Comment by raimohanska** [comment]
Let's assume so then. Thanks for checking! Have a great weekend.
