### ISSUE TITLE
[Feature Request] Backend choice of store

### ISSUE THREAD

**Issue by stormbinary** [raimohanska/ourboard#230]
Hello
It would be very useful if all database functions are isolated with its own defined api. 
That way, data connectors can be built based on the developer's needs.
Just an idea.
Thank you.

**Comment by raimohanska** [comment]
Which storage solution you would like to use and why? Pull requests are welcome :)

**Comment by stormbinary** [comment]
It is not just because I have been away from the relational databases for 10 years and developing using MongoDb. But because I find Mongo 60% faster and uses much less resources on hosting.

**Comment by raimohanska** [comment]
Do you have an OurBoard setup running somewheres, and you would like to improve its performance? So far I haven't found the database to be the problem. Just lately I've improved serverside performance and reliability issues, so if you've experienced issues, please try with the latest code and let me know if it helped!

**Comment by raimohanska** [comment]
All kinds of contributions towards improved performance and reliability are warmly welcome ❤️

**Comment by raimohanska** [comment]
But yeah, I'm not going to do anything about this to be honest. Closing issue for now. If someone really wants to add support for other database backends, you're free to go ahead and I'll be glad to offer support by reviewing the pull requests.
