### ISSUE TITLE
Can not copy objects other than strings

### ISSUE THREAD

**Issue by daipom** [raimohanska/ourboard#246]
# Feature request story or issue

## Screenshot

![Screenshot from 2024-03-06 10-37-03](https://github.com/raimohanska/ourboard/assets/12229857/3a15ea53-e90e-42b9-b3f0-b6dec1e174d3)

## Url

-   Url where you took the screenshot:
-   URL: https://www.ourboard.io/

## A sentence description of the problem

Short DESCRIPTION: Can't copy objects by Ctrl + C or `Clone` button other than strings.

* Can copy a string, but can't copy other objects, such as Area or selected multiple objects.
* It was possible about two weeks ago.  I think the recent fixes could be the cause.

When trying copy, an error log occurs as follows.

```
Uncaught Error: Assertion failed: board not found
    a crdt-store.ts:119
    hp item-cut-copy-paste.ts:42
    a item-cut-copy-paste.ts:179
crdt-store.ts:119:18
    a crdt-store.ts:119
    hp item-cut-copy-paste.ts:42
    a item-cut-copy-paste.ts:179
```

Env:

* OS: Ubuntu 20.04
* Browser: Firefox 123.0

My colleagues using Chrome or Windows have the same problem, so maybe the environment has nothing to do with this issue.

**Comment by raimohanska** [comment]
Hi! Thanks for reporting this bug. Should be fixed now.

Really appreciate you taking the effort to describe the problem so well and sorry for the trouble.

**Comment by raimohanska** [comment]
Fixed in 799c7171ab1a198b4d33f84e8c1bcb5b806d8cae and tests added in 03a7e1e17cc86c74177369cacb3309791d2eb5df.

**Comment by daipom** [comment]
@raimohanska Thank you so much for always responding so quickly!
I have confirmed that it is fixed!
Thanks so much!

**Comment by raimohanska** [comment]
Great! Keep on reporting if you find issues - I'm trying to improve overall quality gradually while working on new features. Other sorts of feedback on usability and features is also welcome.
